default:
  image: node:16.16.0

before_script:
  - apt-get update && apt-get install -y git

build:
  stage: build
  script:
    - git --version
    - npm install
    - npm run build

deploy_dev:
  stage: deploy
  only:
    - dev
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=development --token=$VERCEL_TOKEN
    - vercel deploy --prod --token=$VERCEL_TOKEN

deploy_staging:
  stage: deploy
  only:
    - staging
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - vercel deploy --prod --token=$VERCEL_TOKEN

deploy_production:
  stage: deploy
  only:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel deploy --prod --token=$VERCEL_TOKEN
